services:
  postgres:
    container_name: postgres_homework_db
    image: postgres:16.9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_homework:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres_homework:
    driver: local
